max_seq_length: 40
pretrained_path: "/home/pretrains/pt/bert-base-chinese"
file_path: "/home/zhangqi/project/2023_MERC/dataset/RUCM3ED/text/test/text.txt"
batch_size: 8
version: test-image_bind
max_epochs: 4
devices: 1
mode: test
train_val_test_ratio: [0.8,0.2]
emb_path: ../dataset/RUCM3ED/emb/test
label_path: ../dataset/RUCM3ED/text/test/label.txt
Image_bind: True
learning_rate: 1e-5

