max_seq_length: 40
pretrained_path: "/home/pretrains/pt/bert-base-chinese"
file_path: "/home/zhangqi/project/RUCM3ED/dataset/RUCM3ED/annotation.txt"
batch_size: 4
version: 0
max_epochs: 4
devices: 1
mode: test
train_val_test_ratio: [0.8,0.1,0.1]


