wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 8
max_epochs:
  desc: null
  value: 4
Image_bind:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685704008.773914
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.2
      6: 4.29.1
      8:
      - 5
